baseurl: "/"
collections:
  folder1:
    output: true
    permalink: /brosur/:path/
  # folder1:
  #   output: true
  #   permalink: /brosur/V1/:path/
  # folder1:
  #   output: true
  #   permalink: /brosur/V1/:path/
  # folder2:
  #   output: true
  #   permalink: /brosur/V2/:path/
  # folder3:
  #   output: true
  #   permalink: /brosur/V3/:path/
  # folder4:
  #   output: true
  #   permalink: /brosur/V3.1/:path/
